<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/5/9
 * Time: 16:11
 */

namespace app\admin\model;

use think\Model;


class Article extends Model
{

    /**
     * 上传缩略图
     * 插入文章前 执行这个方法
     */
    protected static function init()
    {
//        parent::init(); // TODO: Change the autogenerated stub
//        $article  这里指的是当前类的实例
        Article::event('before_insert', function ($article) {

            if ($_FILES['pic']['tmp_name']) {
                $file = request()->file('pic');
//                C:\phpStudy\PHPTutorial\WWW\birk\public\static\admin
                $info = $file->move(ROOT_PATH . 'public/static/admin' . DS . 'uploads');
                if ($info) {
                    $article['pic'] = $info->getSaveName();

                }
            }

        });

        Article::event('before_update', function ($article) {

            if ($_FILES['pic']['tmp_name']) {
                $file = request()->file('pic');
//                C:\phpStudy\PHPTutorial\WWW\birk\public\static\admin
                $info = $file->move(ROOT_PATH . 'public/static/admin' . DS . 'uploads');
                if ($info) {
                    $article['pic'] = $info->getSaveName();
                }
            }

        });

    }

}