<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/5/12
 * Time: 15:48
 */

namespace app\admin\controller;

use think\Controller;

class Common extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(!session('admin') || !session('id')){
            $this->error('请先登录!','login/index');
            exit;
        }
    }

}