<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/5/26
 * Time: 10:40
 */

namespace app\index\controller;


use think\Controller;

class Common extends Controller
{
    public function _initialize()
    {
        //这里需要写一下读取网站配置项
//        parent::_initialize(); // TODO: Change the autogenerated stub
//        $conf = new \app\index\model\Conf();
//        $_confres = $conf->getAttrConf();
//        dump($_confres);die;
        //当前位置
        if (input('cateid')) {
            $this->getPos(input('cateid'));
        }
        if (input('artid')) {
            $articles = db('article')->field('cateid')->find(input('artid'));
//            dump($articles);die;
            $artid = $articles['cateid'];

        }


        $cateBottomRec = new \app\index\model\Cate();
        $cateBottomRecs = $cateBottomRec->getBottomRec();


        $this->assign([
            'cateBottomRecs'=>$cateBottomRecs,
        ]);


        $this->getNavcates();

    }

    /**
     * 获取栏目 cate
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function getNavcates()
    {
        $cateres = db('cate')->where(['pid' => 0])->select();
        foreach ($cateres as $k => $v) {
            $children = db('cate')->where(['pid' => $v['id']])->select();
            if ($children) {
                $cateres[$k]['children'] = $children;
            } else {
                $cateres[$k]['children'] = 0;
            }

        }
        $this->assign('cateres', $cateres);

//        dump($cateres);die;
    }


    public function getHosRes($cateid)
    {
        $cate = new \app\index\model\Cate();
//        $
    }

    public function getPos($cateid)
    {

    }

    public function getBottomRec(){
        $cate = new \app\index\model\Cate();
        $cate_bottom_rec = $cate->getBottomRec();
        return $cate_bottom_rec;
    }
}